export const CART_ADD_ITEMS = "CART_ADD_ITEMS";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_SAVE_SHIPPING = "CART_SAVE_SHIPPING";
export const CART_SAVE_PAYMENT = "CART_SAVE_PAYMENT";
